export enum EItemFieldType {
  INPUT = 'INPUT',
  PASSWORD = 'PASSWORD',
  SELECT = 'SELECT',
  MULTI_SELECT = 'MULTI_SELECT',
  TEXTAREA = 'TEXTAREA',
  CHECK_BOX = 'CHECK_BOX',
  SWITCH = 'SWITCH',
  RADIO_GROUP = 'RADIO_GROUP',
  DATE_PICKER = 'DATE_PICKER',
  RANGE_DATE_PICKER = 'RANGE_DATE_PICKER',
  UPLOAD_IMAGE = 'UPLOAD_IMAGE',
}
